from snakemake.utils import min_version

min_version('6.7.0')

##### set minimum snakemake version #####

configfile: 'config/config.yaml'

##### load rules #####
include: 'rules/common.smk'
include: 'rules/mix.smk'
include: 'rules/count.smk'

##### workflow #####

rule all:
    input:
        expand('results/subsampled-sorted/{norm_seed}.{norm}_{seed}/{sample}_0.{prop}.bam.bai',
                zip,
                sample=samples,
                norm_seed=norm_seeds,
                norm=norms,
                seed=seeds,
                prop=props),
        expand('results/merged/{norm_seed1}.{norm1}_{norm_seed2}.{norm2}/{sample1}_0.{prop1}_{sample2}_0.{prop2}.bam.bai',
                zip,
                sample1=recipe.sample1.values,
                norm_seed1=recipe.seed_s1.values,
                norm1=recipe.norms_s1.values,
                seed1=recipe.seed1.values,
                prop1=recipe.prop1.values,
                sample2=recipe.sample2.values,
                norm_seed2=recipe.seed_s2.values,
                norm2=recipe.norms_s2.values,
                seed2=recipe.seed2.values,
                prop2=recipe.prop2.values),
        expand('results/pileup/{norm_seed1}.{norm1}_{norm_seed2}.{norm2}/{sample1}_0.{prop1}_{sample2}_0.{prop2}_pileup.vcf',
                zip,
                sample1=recipe.sample1.values,
                norm_seed1=recipe.seed_s1.values,
                norm1=recipe.norms_s1.values,
                seed1=recipe.seed1.values,
                prop1=recipe.prop1.values,
                sample2=recipe.sample2.values,
                norm_seed2=recipe.seed_s2.values,
                norm2=recipe.norms_s2.values,
                seed2=recipe.seed2.values,
                prop2=recipe.prop2.values)
